# Generated by Django 3.1 on 2020-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200908_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.Comment'),
        ),
    ]
